apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimicrosrv
  labels:
    app: udacityprj41
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacityprj41
  template:
    metadata:
      labels:
        app: udacityprj41
    spec:
      containers:
      - name: prj4
        image: 482389634785.dkr.ecr.us-west-2.amazonaws.com/udacityprj4:latest
        ports:
        - containerPort: 5000